#!/usr/bin/env node
var CertScanner = require('./certScanner');

var argv = require('optimist').argv;

var scanner = new CertScanner(process.argv[2], argv);

scanner.on('notice', function(msg) {
  console.warn(msg);
});

scanner.scan(function(err, config) {
  if(err)
    return console.log(err.stack);
  console.log(config);
});