#!/usr/bin/env node
var CertScanner = require('./certScanner');

var scanner = new CertScanner(process.argv[2]);
scanner.scan(function(err, config) {
  if(err)
    return console.log(err.stack);
  console.log(config);
});